import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by Next for typed routes:
    'types/routes.d.ts',
    // Generated Prisma Client:
    'src/generated/**',
    // Generated by playwright-bdd from the feature files:
    '.features-gen/**',
  ]),
  {
    // Debt that predates lint running in CI. Both stay visible as warnings
    // and are paid down file by file; neither is allowed to grow into a new
    // error type, so the gate still holds everything else.
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
    },
  },
  {
    // playwright-bdd's fixture `use` is Playwright's, not React's.
    files: ['e2e/**'],
    rules: { 'react-hooks/rules-of-hooks': 'off' },
  },
]);

export default eslintConfig;
